version: '3'

services:

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    network_mode: host
    restart: always

  viewer:
    build: .
    network_mode: host
    container_name: capser-viewer
    restart: always
    env_file:
      - settings.env
    depends_on:
      - node-exporter
